version: '2'
services:
    compte-mongodb:
        container_name: compte-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        command: mongos --configdb compte-mongodb-config
    compte-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    compte-mongodb-config:
        image: mongo:3.3.5
        container_name: compte-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
